### ISSUE TITLE
TypeError: Invalid Version: null     at new SemVer 

### ISSUE THREAD

**Issue by tamird** [piuccio/jspm-check-updates#1]
When running from github.com/cockroachdb/cockroach/ui:

```
$(npm bin)/jspm-check-updates
Reading package json
Fetching update info for 28 packages
TypeError: Invalid Version: null
    at new SemVer (/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/node_modules/semver/semver.js:279:11)
    at SemVer.compare (/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/node_modules/semver/semver.js:342:13)
    at compare (/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/node_modules/semver/semver.js:566:31)
    at Function.gt (/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/node_modules/semver/semver.js:595:10)
    at /Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/node_modules/jspm-check-updates/index.js:76:20
    at /Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/node_modules/jspm-check-updates/index.js:112:5
    at Array.forEach (native)
    at iterate (/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/node_modules/jspm-check-updates/index.js:110:23)
    at filterUpdates (/Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/node_modules/jspm-check-updates/index.js:74:2)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by piuccio** [comment]
Fix published in `1.1.2`
